import sys
import unittest
import torch
import json
import numpy as np
from pathlib import Path
from gensim.models import Word2Vec

# Add parent directory to sys.path to allow imports from root folder
ROOT_DIR = Path(__file__).resolve().parent
sys.path.append(str(ROOT_DIR))

import config as root_config
import policy.policy_config as policy_config
from policy.dataset import PolicyDataset
from policy.model import AlphaLMPolicyMLP
from policy.infer import AlphaLMPolicyHead
from search import AlphaLMSearcher, SearchPath
from tokenizer import clean_and_tokenize

class TestAlphaLMPolicy(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.test_dir = ROOT_DIR / "policy_test_temp"
        cls.test_dir.mkdir(parents=True, exist_ok=True)
        
        # 1. Create a mock corpus and train a tiny Word2Vec model
        cls.corpus = [
            "we offer great software promotions today.",
            "our sales representatives will call you.",
            "please consult our pricing guidelines.",
            "check out our product features online."
        ]
        tokenized = [clean_and_tokenize(s) for s in cls.corpus]
        cls.w2v_path = cls.test_dir / "test_w2v.model"
        cls.w2v = Word2Vec(tokenized, vector_size=policy_config.EMBEDDING_DIM, min_count=1, seed=42)
        cls.w2v.save(str(cls.w2v_path))
        
        # 2. Create a mock policy data JSON
        cls.mock_data = [
            {
                "context": [cls.corpus[0], cls.corpus[1]],
                "candidate": cls.corpus[2],
                "boundary_score": 0.5,
                "local_coherence": 0.8,
                "global_coherence": 0.7,
                "makes_sense_score": 0.9,
                "score": 2.5,
                "label": 1.0
            },
            {
                "context": [cls.corpus[0], cls.corpus[1]],
                "candidate": cls.corpus[3],
                "boundary_score": 0.1,
                "local_coherence": 0.2,
                "global_coherence": 0.3,
                "makes_sense_score": 0.1,
                "score": 0.7,
                "label": 0.0
            }
        ]
        cls.json_path = cls.test_dir / "mock_policy_data.json"
        with open(cls.json_path, "w", encoding="utf-8") as f:
            json.dump(cls.mock_data, f)
            
        # 3. Save a mock model checkpoint
        input_dim = policy_config.WINDOW_SIZE * policy_config.EMBEDDING_DIM
        cls.model = AlphaLMPolicyMLP(input_dim=input_dim, hidden_layers=[16, 8], dropout=0.0)
        cls.checkpoint_path = cls.test_dir / "test_policy_head.pt"
        torch.save(cls.model.state_dict(), str(cls.checkpoint_path))

    @classmethod
    def tearDownClass(cls):
        # Clean up temporary test files
        if cls.w2v_path.exists():
            cls.w2v_path.unlink()
        if cls.json_path.exists():
            cls.json_path.unlink()
        if cls.checkpoint_path.exists():
            cls.checkpoint_path.unlink()
        # Clean up temporary word2vec files if any are generated by gensim
        for f in cls.test_dir.glob("test_w2v.model*"):
            f.unlink()
        if cls.test_dir.exists():
            cls.test_dir.rmdir()

    def test_policy_config(self):
        """Test config variables are defined and type-consistent."""
        self.assertEqual(policy_config.WINDOW_SIZE, 4)
        self.assertEqual(policy_config.EMBEDDING_DIM, 100)
        self.assertTrue(isinstance(policy_config.HIDDEN_LAYERS, list))
        
    def test_model_forward(self):
        """Test policy model forward pass and output bounds."""
        input_dim = policy_config.WINDOW_SIZE * policy_config.EMBEDDING_DIM
        model = AlphaLMPolicyMLP(input_dim=input_dim, hidden_layers=[32, 16], dropout=0.1)
        dummy_x = torch.randn(4, input_dim)
        output = model(dummy_x)
        self.assertEqual(output.shape, (4, 1))
        self.assertTrue(torch.all(output >= 0.0))
        self.assertTrue(torch.all(output <= 1.0))

    def test_dataset_without_scalars(self):
        """Test dataset loading and feature shapes without scalar features."""
        dataset = PolicyDataset(self.json_path, self.w2v_path, use_scalar_features=False)
        self.assertEqual(len(dataset), 2)
        x, y = dataset[0]
        expected_dim = policy_config.WINDOW_SIZE * policy_config.EMBEDDING_DIM
        self.assertEqual(x.shape, (expected_dim,))
        self.assertEqual(y.shape, (1,))

    def test_dataset_with_scalars(self):
        """Test dataset loading and feature shapes with scalar features."""
        dataset = PolicyDataset(self.json_path, self.w2v_path, use_scalar_features=True)
        self.assertEqual(len(dataset), 2)
        x, y = dataset[0]
        expected_dim = policy_config.WINDOW_SIZE * policy_config.EMBEDDING_DIM + policy_config.NUM_SCALAR_FEATURES
        self.assertEqual(x.shape, (expected_dim,))
        self.assertEqual(y.shape, (1,))

    def test_policy_head_inference(self):
        """Test policy head wrapper initialization and batch candidate scoring."""
        policy_head = AlphaLMPolicyHead(model_path=self.checkpoint_path, w2v_path=self.w2v_path, hidden_layers=[16, 8])
        
        # Override use_scalar parameter on model/head wrapper to match mock config
        policy_head.use_scalar = False
        
        history = [self.corpus[0], self.corpus[1]]
        candidates = [self.corpus[2], self.corpus[3]]
        
        scores = policy_head.score_candidates(history, candidates)
        self.assertEqual(len(scores), 2)
        for s in scores:
            self.assertTrue(0.0 <= s <= 1.0)

    def test_search_integration_with_policy(self):
        """Test beam search integration when policy head is active."""
        policy_head = AlphaLMPolicyHead(model_path=self.checkpoint_path, w2v_path=self.w2v_path, hidden_layers=[16, 8])
        policy_head.use_scalar = False

        
        searcher = AlphaLMSearcher(
            corpus_sentences=self.corpus,
            w2v_model=self.w2v,
            makes_sense_evaluator=None,
            policy_head=policy_head
        )
        
        # Test search run with active policy weights
        weights = {
            "boundary": 1.0,
            "local": 0.5,
            "global": 0.5,
            "completion": 0.0,
            "makes_sense": 0.0,
            "policy": 1.0
        }
        
        best_path, step_logs = searcher.search(
            seed_idx=0,
            num_sentences=3,
            beam_width=2,
            weights=weights
        )
        
        self.assertEqual(len(best_path.sentence_indices), 3)
        self.assertEqual(len(best_path.policy_scores), 2)
        for s in best_path.policy_scores:
            self.assertTrue(0.0 <= s <= 1.0)
            
if __name__ == "__main__":
    unittest.main()
