"""Convert wozformer_hdcrwkv_v3.bin (+ deterministic BPE) → C headers for ESP8266.

This script reads the shipping binary and re-trains the BPE tokenizer on
Tiny Shakespeare with the same parameters used in nb12c. BPE training is
deterministic for a fixed (corpus, vocab_size) pair so the resulting tokens
are identical to what was used to train the model.

Outputs in this directory:
  model_data.h  — vocab/prototype/decay hypervectors as PROGMEM byte arrays
  bpe_tables.h  — vocab strings + BPE merges as PROGMEM lookup tables

Usage:
  cd firmware/arduino/wozformer_esp8266
  python export_to_c.py
"""
from __future__ import annotations

import struct
from collections import Counter
from pathlib import Path

# Paths
HERE = Path(__file__).parent
ROOT = HERE.parent.parent.parent
BIN_PATH = ROOT / "export" / "wozformer_hdcrwkv_v3.bin"
CORPUS_PATH = ROOT / "data" / "tinyshakespeare.txt"

assert BIN_PATH.exists(), f"missing {BIN_PATH}"
assert CORPUS_PATH.exists(), f"missing {CORPUS_PATH}"

# ---------- Parse the .bin --------------------------------------------------
buf = BIN_PATH.read_bytes()
assert buf[:4] == b"WHR3", f"bad magic: {buf[:4]!r}"
version = buf[4]
vocab_size = struct.unpack("<H", buf[5:7])[0]
d_bytes = struct.unpack("<H", buf[7:9])[0]
D = d_bytes * 8
block_size = buf[9]
n_layers = buf[10]
log_temp = struct.unpack("<f", buf[11:15])[0]
HEADER_LEN = 18

print("model header:")
print(f"  version={version}  vocab={vocab_size}  D={D} bits ({d_bytes} B/vec)")
print(f"  block={block_size}  layers={n_layers}  log_temp={log_temp:.4f}")

expected = HEADER_LEN + 2 * vocab_size * d_bytes + n_layers * d_bytes
assert len(buf) == expected, f"size mismatch: {len(buf)} vs {expected}"

off = HEADER_LEN
vocab_bytes = buf[off : off + vocab_size * d_bytes]; off += vocab_size * d_bytes
proto_bytes = buf[off : off + vocab_size * d_bytes]; off += vocab_size * d_bytes
decay_bytes = buf[off : off + n_layers * d_bytes]

# ---------- Re-train BPE deterministically ---------------------------------
EOW = "</w>"
text = CORPUS_PATH.read_text(encoding="utf-8", errors="ignore").replace("\r\n", "\n").strip().lower()
print(f"\nRetraining BPE on {len(text):,} chars to vocab={vocab_size}...")

def train_bpe(text, num_merges):
    word_freq = Counter(tuple(list(w) + [EOW]) for w in text.split())
    word_lists = {w: list(w) for w in word_freq}
    merges = []
    for _ in range(num_merges):
        pair_counts = Counter()
        for w, freq in word_freq.items():
            sym = word_lists[w]
            for i in range(len(sym) - 1):
                pair_counts[(sym[i], sym[i + 1])] += freq
        if not pair_counts:
            break
        best, _ = pair_counts.most_common(1)[0]
        new_tok = best[0] + best[1]
        merges.append((best, new_tok))
        for w in word_freq:
            sym = word_lists[w]; new_sym = []; i = 0
            while i < len(sym):
                if i < len(sym) - 1 and (sym[i], sym[i + 1]) == best:
                    new_sym.append(new_tok); i += 2
                else:
                    new_sym.append(sym[i]); i += 1
            word_lists[w] = new_sym
    vocab_set = set()
    for w in word_freq:
        vocab_set.update(word_lists[w])
        vocab_set.update(w)
    return merges, sorted(vocab_set)

# nb12c used 215 merges to land at vocab=256
NUM_MERGES = 215
merges, vocab = train_bpe(text, NUM_MERGES)
all_toks = ["<unk>"] + sorted(vocab)
while len(all_toks) < vocab_size:
    all_toks.append(f"<pad{len(all_toks)}>")
itos = all_toks[:vocab_size]
print(f"BPE: {len(merges)} merges, vocab={len(itos)} tokens")
print(f"longest 5 tokens: {sorted(itos, key=lambda x: -len(x))[:5]}")

# ---------- Helper: emit a C PROGMEM byte array ----------------------------
def emit_bytes(name, data, line_width=16):
    lines = [f"const unsigned char PROGMEM {name}[{len(data)}] = {{"]
    for i in range(0, len(data), line_width):
        chunk = data[i : i + line_width]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)

# ---------- Write model_data.h ---------------------------------------------
mh = [
    "// AUTO-GENERATED by export_to_c.py — do not edit by hand.",
    "// HDC-RWKV bipolar weights for ESP8266/ESP32 (1 bit per dim, packed MSB-first).",
    "#pragma once",
    "#include <Arduino.h>",
    "",
    f"#define WOZ_VOCAB        {vocab_size}",
    f"#define WOZ_D            {D}",
    f"#define WOZ_D_BYTES      {d_bytes}",
    f"#define WOZ_BLOCK_SIZE   {block_size}",
    f"#define WOZ_N_LAYERS     {n_layers}",
    f"const float WOZ_LOG_TEMP = {log_temp}f;",
    "",
    emit_bytes("woz_vocab_hv", vocab_bytes),
    "",
    emit_bytes("woz_prototype_hv", proto_bytes),
    "",
    emit_bytes("woz_decay_mask", decay_bytes),
    "",
]
(HERE / "model_data.h").write_text("\n".join(mh))
print(f"\nwrote model_data.h  ({len(vocab_bytes) + len(proto_bytes) + len(decay_bytes):,} B of model)")

# ---------- Write bpe_tables.h ---------------------------------------------
# Flat string blob + offset table — saves flash vs. pointer arrays.
itos_blob = bytearray()
itos_offsets = []
for s in itos:
    itos_offsets.append(len(itos_blob))
    itos_blob += s.encode("utf-8") + b"\x00"

merges_blob = bytearray()
merges_offsets = []  # triples (a_off, b_off, merged_off) flattened
for (a, b), merged in merges:
    a_off = len(merges_blob); merges_blob += a.encode("utf-8") + b"\x00"
    b_off = len(merges_blob); merges_blob += b.encode("utf-8") + b"\x00"
    m_off = len(merges_blob); merges_blob += merged.encode("utf-8") + b"\x00"
    merges_offsets.extend([a_off, b_off, m_off])

bh = [
    "// AUTO-GENERATED by export_to_c.py — do not edit by hand.",
    "// BPE tokenizer for HDC-RWKV.",
    "#pragma once",
    "#include <Arduino.h>",
    "",
    f"#define BPE_NUM_MERGES   {len(merges)}",
    '#define BPE_EOW          "</w>"',
    "",
    "// itos: flat blob of null-terminated UTF-8 strings.",
    emit_bytes("bpe_itos_blob", list(itos_blob)),
    "",
    f"const uint16_t PROGMEM bpe_itos_offsets[{len(itos_offsets)}] = {{",
]
for i in range(0, len(itos_offsets), 16):
    chunk = itos_offsets[i : i + 16]
    bh.append("  " + ", ".join(str(x) for x in chunk) + ",")
bh.append("};")
bh.append("")
bh.append("// merges: flat blob; offsets[i*3..i*3+2] = (a, b, merged) byte offsets.")
bh.append(emit_bytes("bpe_merges_blob", list(merges_blob)))
bh.append("")
bh.append(f"const uint16_t PROGMEM bpe_merges_offsets[{len(merges_offsets)}] = {{")
for i in range(0, len(merges_offsets), 15):
    chunk = merges_offsets[i : i + 15]
    bh.append("  " + ", ".join(str(x) for x in chunk) + ",")
bh.append("};")
bh.append("")

(HERE / "bpe_tables.h").write_text("\n".join(bh))
print(f"wrote bpe_tables.h  (itos blob {len(itos_blob):,} B + merges blob {len(merges_blob):,} B)")

# ---------- Summary --------------------------------------------------------
print("\n" + "=" * 60)
print("Summary")
print("=" * 60)
print(f"Model:         {len(vocab_bytes) + len(proto_bytes) + len(decay_bytes):>6,} bytes")
print(f"BPE itos:      {len(itos_blob):>6,} bytes")
print(f"BPE merges:    {len(merges_blob):>6,} bytes")
print(f"BPE offsets:   {len(itos_offsets)*2 + len(merges_offsets)*2:>6,} bytes")
total = (
    len(vocab_bytes) + len(proto_bytes) + len(decay_bytes)
    + len(itos_blob) + len(merges_blob)
    + len(itos_offsets) * 2 + len(merges_offsets) * 2
)
print(f"TOTAL flash:   {total:>6,} bytes (~{total / 1024:.1f} KB)")
print("ESP8266 NodeMCU has 4 MB flash — easy fit.")
