"""Convert wozformer_hdcrwkv_v3.bin + .pt → C headers for ESP8266 firmware.

Outputs:
  model_data.h   — packed vocab/prototype/decay bits as PROGMEM byte arrays
  bpe_tables.h   — vocab strings + BPE merges as PROGMEM lookup tables

Usage:
  python export_to_c.py
  (run from this directory; reads ../../../export/wozformer_hdcrwkv_v3.{bin,pt})
"""
import struct, json
from pathlib import Path

# Need torch only for loading the .pt (the .bin is plain bytes)
import torch

HERE = Path(__file__).parent
EXPORT = HERE.parent.parent.parent / 'export'

BIN_PATH = EXPORT / 'wozformer_hdcrwkv_v3.bin'
PT_PATH  = EXPORT / 'wozformer_hdcrwkv_v3.pt'

assert BIN_PATH.exists(), f'missing {BIN_PATH}'
assert PT_PATH.exists(),  f'missing {PT_PATH} — run nb12c save cell first'

# -- Parse the .bin (just to confirm header values; we'll embed the raw bytes) --
buf = BIN_PATH.read_bytes()
assert buf[:4] == b'WHR3', f'bad magic: {buf[:4]!r}'
version    = buf[4]
vocab_size = struct.unpack('<H', buf[5:7])[0]
d_bytes    = struct.unpack('<H', buf[7:9])[0]
D          = d_bytes * 8
block_size = buf[9]
n_layers   = buf[10]
log_temp   = struct.unpack('<f', buf[11:15])[0]
# bytes 15-17 reserved
HEADER_LEN = 18

print(f'parsed header:')
print(f'  version={version}, vocab={vocab_size}, D={D} ({d_bytes} bytes/vec)')
print(f'  block={block_size}, layers={n_layers}, log_temp={log_temp:.4f}')

# Sanity: file size should be HEADER + vocab + proto + decay
expected = HEADER_LEN + 2 * vocab_size * d_bytes + n_layers * d_bytes
assert len(buf) == expected, f'size mismatch: {len(buf)} vs {expected}'

# Slice into bytes views
off = HEADER_LEN
vocab_bytes = buf[off : off + vocab_size * d_bytes];  off += vocab_size * d_bytes
proto_bytes = buf[off : off + vocab_size * d_bytes];  off += vocab_size * d_bytes
decay_bytes = buf[off : off + n_layers * d_bytes]

# -- Parse the .pt for BPE merges + itos --
ckpt = torch.load(PT_PATH, map_location='cpu', weights_only=False)
itos    = ckpt['itos']
merges  = ckpt['merges']      # list of ((a, b), merged)
EOW     = ckpt.get('EOW', '</w>')

assert len(itos) == vocab_size, f'vocab mismatch: {len(itos)} vs {vocab_size}'

# -- Helper: emit a C byte array PROGMEM --
def emit_byte_array(name, data, line_width=16):
    lines = [f'const unsigned char PROGMEM {name}[{len(data)}] = {{']
    for i in range(0, len(data), line_width):
        chunk = data[i:i + line_width]
        lines.append('  ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',')
    lines.append('};')
    return '\n'.join(lines)

# -- Write model_data.h --
model_h = []
model_h.append('// AUTO-GENERATED by export_to_c.py — do not edit by hand.')
model_h.append('// HDC-RWKV model weights (bipolar, bit-packed).')
model_h.append('#pragma once')
model_h.append('#include <Arduino.h>')
model_h.append('')
model_h.append(f'#define WOZ_VOCAB_SIZE   {vocab_size}')
model_h.append(f'#define WOZ_D            {D}')
model_h.append(f'#define WOZ_D_BYTES      {d_bytes}')
model_h.append(f'#define WOZ_BLOCK_SIZE   {block_size}')
model_h.append(f'#define WOZ_N_LAYERS     {n_layers}')
model_h.append(f'const float WOZ_LOG_TEMP = {log_temp}f;')
model_h.append('')
model_h.append(emit_byte_array('woz_vocab_hv',     vocab_bytes))
model_h.append('')
model_h.append(emit_byte_array('woz_prototype_hv', proto_bytes))
model_h.append('')
model_h.append(emit_byte_array('woz_decay_mask',   decay_bytes))
model_h.append('')

(HERE / 'model_data.h').write_text('\n'.join(model_h))
print(f'wrote model_data.h  ({len(vocab_bytes) + len(proto_bytes) + len(decay_bytes):,} bytes of weight data)')

# -- Write bpe_tables.h --
# Format we'll use:
#   const char* itos[VOCAB] = { "a", "b", ..., "the</w>", ... };
#   For merges: pack as a single string blob with offsets, to avoid the cost
#   of ~215 separate string pointer entries.
#
# But the simplest readable format: emit each merge as three short strings.

bpe_h = []
bpe_h.append('// AUTO-GENERATED by export_to_c.py — do not edit by hand.')
bpe_h.append('// BPE tokenizer: itos table + merge rules.')
bpe_h.append('#pragma once')
bpe_h.append('#include <Arduino.h>')
bpe_h.append(f'#include <pgmspace.h>')
bpe_h.append('')
bpe_h.append(f'#define BPE_NUM_MERGES   {len(merges)}')
bpe_h.append(f'#define BPE_EOW          "{EOW}"')
bpe_h.append('')

# itos: array of PROGMEM strings, indexed by token id.
# We declare each string as a static const PROGMEM array, then collect pointers.
def escape_c(s):
    out = []
    for ch in s:
        if ch == '\\':  out.append('\\\\')
        elif ch == '"': out.append('\\"')
        elif ch == '\n': out.append('\\n')
        elif ch == '\t': out.append('\\t')
        elif 32 <= ord(ch) < 127: out.append(ch)
        else: out.append(f'\\x{ord(ch):02x}')
    return ''.join(out)

# Emit itos as a flat string blob with offsets to save flash:
itos_blob = bytearray()
itos_offsets = []
for s in itos:
    itos_offsets.append(len(itos_blob))
    itos_blob += s.encode('utf-8')
    itos_blob += b'\x00'  # null terminator

bpe_h.append(f'// itos: flat blob of null-terminated UTF-8 strings + offset table.')
bpe_h.append(emit_byte_array('bpe_itos_blob', list(itos_blob)))
bpe_h.append('')
bpe_h.append(f'const uint16_t PROGMEM bpe_itos_offsets[{len(itos_offsets)}] = {{')
for i in range(0, len(itos_offsets), 16):
    chunk = itos_offsets[i:i+16]
    bpe_h.append('  ' + ', '.join(str(x) for x in chunk) + ',')
bpe_h.append('};')
bpe_h.append('')

# Merges: pack as flat blob too — for each merge we need (a, b, merged) strings.
merges_blob = bytearray()
merges_offsets = []  # (a_off, b_off, m_off) triples flattened
for (a, b), m in merges:
    a_off = len(merges_blob); merges_blob += a.encode('utf-8') + b'\x00'
    b_off = len(merges_blob); merges_blob += b.encode('utf-8') + b'\x00'
    m_off = len(merges_blob); merges_blob += m.encode('utf-8') + b'\x00'
    merges_offsets.extend([a_off, b_off, m_off])

bpe_h.append(f'// merges: flat blob; offsets[i*3..i*3+2] = (a, b, merged) byte offsets.')
bpe_h.append(emit_byte_array('bpe_merges_blob', list(merges_blob)))
bpe_h.append('')
bpe_h.append(f'const uint16_t PROGMEM bpe_merges_offsets[{len(merges_offsets)}] = {{')
for i in range(0, len(merges_offsets), 15):  # 3 per merge, 5 merges per line
    chunk = merges_offsets[i:i+15]
    bpe_h.append('  ' + ', '.join(str(x) for x in chunk) + ',')
bpe_h.append('};')
bpe_h.append('')

(HERE / 'bpe_tables.h').write_text('\n'.join(bpe_h))
print(f'wrote bpe_tables.h  (itos blob {len(itos_blob):,} B + merges blob {len(merges_blob):,} B)')

# -- Summary --
print()
print('=' * 60)
print('Summary')
print('=' * 60)
print(f'Model weights:    {len(vocab_bytes) + len(proto_bytes) + len(decay_bytes):>6,} bytes')
print(f'BPE itos blob:    {len(itos_blob):>6,} bytes')
print(f'BPE merges blob:  {len(merges_blob):>6,} bytes')
print(f'BPE offsets:      {len(itos_offsets)*2 + len(merges_offsets)*2:>6,} bytes')
total = (len(vocab_bytes) + len(proto_bytes) + len(decay_bytes)
         + len(itos_blob) + len(merges_blob)
         + len(itos_offsets)*2 + len(merges_offsets)*2)
print(f'TOTAL flash:      {total:>6,} bytes (~{total/1024:.1f} KB)')
print(f'ESP8266 flash budget: 1 MB program / 3 MB filesystem (NodeMCU default)')
print(f'Headroom: enormous.')
